POST localhost:3000/testdata

###

PUT localhost:3000/put
Content-Type: application/json

{
  "positionX": 2,
  "positionY": 2,
  "objectType": 0
}

###
PUT localhost:3000/move-grid-object
Content-Type: application/json

{
  "oldX": 100,
  "oldY": 100,
  "newX": 0,
  "newY": 0
}

###
GET localhost:3000/grid-objects


###

PUT localhost:3000/sell
Content-Type: application/json

{
  "positionX": 5,
  "positionY": 4,
  "value": 2000000
}
